import { apiClient } from "./client";
import { ENDPOINTS } from "@/constants/endpoints";

export type AlertSeverity = "critical" | "warning" | "info";

export type AlertSource = "rule" | "ai";

export interface AlertItem {
  id: string;
  title: string;
  device: string;
  time: string;
  severity: AlertSeverity;
  message: string;
  acknowledged: boolean;
  /** "ai" for insights generated by the AI Advisory background service. */
  source?: AlertSource;
  /** 0–1 confidence, only present on AI insights. */
  confidence?: number | null;
  /** Cluster/category label, only present on AI insights. */
  category?: string;
  /** Actionable next step, only present on AI insights. */
  recommendation?: string;
  /** Supporting data points, only present on AI insights. */
  evidence?: string[];
}

export interface AlertsResponse {
  alerts: AlertItem[];
  generated_at: string;
}

export function getAlerts(): Promise<AlertsResponse> {
  return apiClient.get<AlertsResponse>(ENDPOINTS.alerts);
}
