// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: telemetry_envelope.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryEnvelope is the canonical message shape for every device class.
// Tier 1 (Linux, Windows): generated Go struct via protoc-gen-go.
// Tier 2 (IoT, PLC): generated C/Rust headers via protoc-gen-c / protoc-gen-rust.
// No consumer hand-writes this struct.
type TelemetryEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ── Identity ────────────────────────────────
	SchemaVersion    string `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`          // e.g. "1.0"
	CollectorVersion string `protobuf:"bytes,2,opt,name=collector_version,json=collectorVersion,proto3" json:"collector_version,omitempty"` // agent binary semver
	DeviceId         string `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                         // registered device_id, matches JWT claim
	DeviceClass      string `protobuf:"bytes,4,opt,name=device_class,json=deviceClass,proto3" json:"device_class,omitempty"`                // "linux" | "windows" | "iot" | "plc"
	OperatingSystem  string `protobuf:"bytes,5,opt,name=operating_system,json=operatingSystem,proto3" json:"operating_system,omitempty"`    // e.g. "Ubuntu 22.04"
	Hostname         string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// ── Timing ──────────────────────────────────
	WindowStartMs int64 `protobuf:"varint,7,opt,name=window_start_ms,json=windowStartMs,proto3" json:"window_start_ms,omitempty"` // epoch ms, start of collection window
	WindowEndMs   int64 `protobuf:"varint,8,opt,name=window_end_ms,json=windowEndMs,proto3" json:"window_end_ms,omitempty"`       // epoch ms, end of collection window
	// ── Core metrics (all device classes) ───────
	CpuUsage        float32 `protobuf:"fixed32,9,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                      // 0.0–100.0
	MemoryUsage     float32 `protobuf:"fixed32,10,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`            // 0.0–100.0
	NetworkSent     int64   `protobuf:"varint,11,opt,name=network_sent,json=networkSent,proto3" json:"network_sent,omitempty"`             // bytes
	NetworkReceived int64   `protobuf:"varint,12,opt,name=network_received,json=networkReceived,proto3" json:"network_received,omitempty"` // bytes
	// ── Workstation extensions ───────────────────
	GpuUsage       float32 `protobuf:"fixed32,20,opt,name=gpu_usage,json=gpuUsage,proto3" json:"gpu_usage,omitempty"`                     // 0.0–100.0, 0 if absent
	CpuTempCelsius float32 `protobuf:"fixed32,21,opt,name=cpu_temp_celsius,json=cpuTempCelsius,proto3" json:"cpu_temp_celsius,omitempty"` // 0 if sensor unavailable
	// ── Server extensions ────────────────────────
	LoadAverage_1M float32 `protobuf:"fixed32,30,opt,name=load_average_1m,json=loadAverage1m,proto3" json:"load_average_1m,omitempty"`
	ProcessCount   int32   `protobuf:"varint,31,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	// ── Process / workload telemetry ─────────────
	// Per-process samples used for workload & service carbon attribution.
	// Populated by Tier 1 agents; empty on constrained Tier 2 devices.
	Processes []*ProcessSample `protobuf:"bytes,50,rep,name=processes,proto3" json:"processes,omitempty"`
	// ── IoT extensions (Tier 2) ─────────────────
	BatteryVoltage float32 `protobuf:"fixed32,40,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`
	SensorValue    float32 `protobuf:"fixed32,41,opt,name=sensor_value,json=sensorValue,proto3" json:"sensor_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelemetryEnvelope) Reset() {
	*x = TelemetryEnvelope{}
	mi := &file_telemetry_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEnvelope) ProtoMessage() {}

func (x *TelemetryEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEnvelope.ProtoReflect.Descriptor instead.
func (*TelemetryEnvelope) Descriptor() ([]byte, []int) {
	return file_telemetry_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryEnvelope) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *TelemetryEnvelope) GetCollectorVersion() string {
	if x != nil {
		return x.CollectorVersion
	}
	return ""
}

func (x *TelemetryEnvelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryEnvelope) GetDeviceClass() string {
	if x != nil {
		return x.DeviceClass
	}
	return ""
}

func (x *TelemetryEnvelope) GetOperatingSystem() string {
	if x != nil {
		return x.OperatingSystem
	}
	return ""
}

func (x *TelemetryEnvelope) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TelemetryEnvelope) GetWindowStartMs() int64 {
	if x != nil {
		return x.WindowStartMs
	}
	return 0
}

func (x *TelemetryEnvelope) GetWindowEndMs() int64 {
	if x != nil {
		return x.WindowEndMs
	}
	return 0
}

func (x *TelemetryEnvelope) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TelemetryEnvelope) GetMemoryUsage() float32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *TelemetryEnvelope) GetNetworkSent() int64 {
	if x != nil {
		return x.NetworkSent
	}
	return 0
}

func (x *TelemetryEnvelope) GetNetworkReceived() int64 {
	if x != nil {
		return x.NetworkReceived
	}
	return 0
}

func (x *TelemetryEnvelope) GetGpuUsage() float32 {
	if x != nil {
		return x.GpuUsage
	}
	return 0
}

func (x *TelemetryEnvelope) GetCpuTempCelsius() float32 {
	if x != nil {
		return x.CpuTempCelsius
	}
	return 0
}

func (x *TelemetryEnvelope) GetLoadAverage_1M() float32 {
	if x != nil {
		return x.LoadAverage_1M
	}
	return 0
}

func (x *TelemetryEnvelope) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *TelemetryEnvelope) GetProcesses() []*ProcessSample {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *TelemetryEnvelope) GetBatteryVoltage() float32 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *TelemetryEnvelope) GetSensorValue() float32 {
	if x != nil {
		return x.SensorValue
	}
	return 0
}

// A single process observation within the collection window.
// cpu_percent is the machine-wide share (0.0–100.0) consumed by this
// process over the window — the sum across processes ≈ envelope.cpu_usage.
type ProcessSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                 // executable / process name
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`                           // mapped workload (systemd unit, service name, container)
	CpuPercent    float32                `protobuf:"fixed32,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // machine-wide CPU % over the window
	RssBytes      int64                  `protobuf:"varint,5,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`        // resident set size at sample time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSample) Reset() {
	*x = ProcessSample{}
	mi := &file_telemetry_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSample) ProtoMessage() {}

func (x *ProcessSample) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSample.ProtoReflect.Descriptor instead.
func (*ProcessSample) Descriptor() ([]byte, []int) {
	return file_telemetry_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessSample) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessSample) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ProcessSample) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessSample) GetRssBytes() int64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

var File_telemetry_envelope_proto protoreflect.FileDescriptor

const file_telemetry_envelope_proto_rawDesc = "" +
	"\n" +
	"\x18telemetry_envelope.proto\x12\x12ecotrace.telemetry\"\xe9\x05\n" +
	"\x11TelemetryEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12+\n" +
	"\x11collector_version\x18\x02 \x01(\tR\x10collectorVersion\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12!\n" +
	"\fdevice_class\x18\x04 \x01(\tR\vdeviceClass\x12)\n" +
	"\x10operating_system\x18\x05 \x01(\tR\x0foperatingSystem\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\x12&\n" +
	"\x0fwindow_start_ms\x18\a \x01(\x03R\rwindowStartMs\x12\"\n" +
	"\rwindow_end_ms\x18\b \x01(\x03R\vwindowEndMs\x12\x1b\n" +
	"\tcpu_usage\x18\t \x01(\x02R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\n" +
	" \x01(\x02R\vmemoryUsage\x12!\n" +
	"\fnetwork_sent\x18\v \x01(\x03R\vnetworkSent\x12)\n" +
	"\x10network_received\x18\f \x01(\x03R\x0fnetworkReceived\x12\x1b\n" +
	"\tgpu_usage\x18\x14 \x01(\x02R\bgpuUsage\x12(\n" +
	"\x10cpu_temp_celsius\x18\x15 \x01(\x02R\x0ecpuTempCelsius\x12&\n" +
	"\x0fload_average_1m\x18\x1e \x01(\x02R\rloadAverage1m\x12#\n" +
	"\rprocess_count\x18\x1f \x01(\x05R\fprocessCount\x12?\n" +
	"\tprocesses\x182 \x03(\v2!.ecotrace.telemetry.ProcessSampleR\tprocesses\x12'\n" +
	"\x0fbattery_voltage\x18( \x01(\x02R\x0ebatteryVoltage\x12!\n" +
	"\fsensor_value\x18) \x01(\x02R\vsensorValue\"\x8d\x01\n" +
	"\rProcessSample\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x02R\n" +
	"cpuPercent\x12\x1b\n" +
	"\trss_bytes\x18\x05 \x01(\x03R\brssBytesB\"Z github.com/Ecotrace/agent/schemab\x06proto3"

var (
	file_telemetry_envelope_proto_rawDescOnce sync.Once
	file_telemetry_envelope_proto_rawDescData []byte
)

func file_telemetry_envelope_proto_rawDescGZIP() []byte {
	file_telemetry_envelope_proto_rawDescOnce.Do(func() {
		file_telemetry_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_envelope_proto_rawDesc), len(file_telemetry_envelope_proto_rawDesc)))
	})
	return file_telemetry_envelope_proto_rawDescData
}

var file_telemetry_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_envelope_proto_goTypes = []any{
	(*TelemetryEnvelope)(nil), // 0: ecotrace.telemetry.TelemetryEnvelope
	(*ProcessSample)(nil),     // 1: ecotrace.telemetry.ProcessSample
}
var file_telemetry_envelope_proto_depIdxs = []int32{
	1, // 0: ecotrace.telemetry.TelemetryEnvelope.processes:type_name -> ecotrace.telemetry.ProcessSample
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_envelope_proto_init() }
func file_telemetry_envelope_proto_init() {
	if File_telemetry_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_envelope_proto_rawDesc), len(file_telemetry_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_envelope_proto_goTypes,
		DependencyIndexes: file_telemetry_envelope_proto_depIdxs,
		MessageInfos:      file_telemetry_envelope_proto_msgTypes,
	}.Build()
	File_telemetry_envelope_proto = out.File
	file_telemetry_envelope_proto_goTypes = nil
	file_telemetry_envelope_proto_depIdxs = nil
}
